#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     sensorIR,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S2,     sensorUltrasonic, sensorSONAR)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S4_C1_1,     motorRight,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S4_C1_2,     motorLeft,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S3_C1_1,    servoArmPitch,        tServoContinuousRotation)
#pragma config(Servo,  srvo_S3_C1_2,    servoArmSegment,      tServoContinuousRotation)
#pragma config(Servo,  srvo_S3_C1_3,    servoGripper,         tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// The Doppler Effect 2013
// Teleop 2

#include "JoystickDriver.c"
#include "Teleop.h"

volatile float averageRuntime;
volatile int averageRuntimeCount;

volatile int driveMaxSpeed;

volatile int driveSpeedLeft;
volatile int driveSpeedRight;

volatile int gripperState;

volatile int servoArmPitchValue;
volatile int servoArmSegmentValue;

// Initializations
void initialize() {
	averageRuntime = 0.0;
	averageRuntimeCount = 0;
	driveMaxSpeed = 100;
	driveSpeedLeft = 0;
	driveSpeedRight = 0;
	gripperState = 0;
	servoArmPitchValue = 0;
	servoArmSegmentValue = 0;
}

// Main task
task main() {
	initialize();

	// Wait for the field control system
	waitForStart();

	// Start subroutines
	StartTask(controller);
	StartTask(screen);

	while (true) {
		averageRuntimeCount++;

		if (averageRuntimeCount > MAX_AVG_RUNTIME_CNT) {
			averageRuntimeCount = 1;
			averageRuntime = 0;
		}

		averageRuntime = (averageRuntime + time1[T1]/1000.0)/averageRuntimeCount;

		ClearTimer(T1);

		// Set state of motor
		motor[motorLeft]        = driveSpeedLeft;
		motor[motorRight]       = driveSpeedRight;

		servo[servoArmPitch]    = servoArmPitchValue;
		servo[servoArmSegment]  = servoArmSegmentValue;

		// Set state of gripper
		if (gripperState == 0) {
			servo[servoGripper] = SERVO_GRIPPER_CLOSED_POS;
		} else if (gripperState == 1) {
			servo[servoGripper] = SERVO_GRIPPER_OPEN_POS;
		}

		// Allow other tasks to run
		EndTimeSlice();
	}
}

// Controller task
// Responsible for sampling data from the controllers, making decisions, and sending commands to the main task
task controller() {
	while (true) {
		// Poll joystick data
		getJoystickSettings(joystick);

		// Handle joystick state
		driveSpeedLeft  = ((float) joystick.joy1_y1/128.0)*driveMaxSpeed;
		driveSpeedRight = ((float) joystick.joy1_y2/128.0)*driveMaxSpeed;

		// Handle button state
		driveMaxSpeed = (joy1Btn(BUTTON_R1) == 0) ? MOTOR_DRIVE_HIGH_SPEED : MOTOR_DRIVE_LOW_SPEED;

		// Gripper buttons on controller 2
		// Continue if one is pressed, but not the other
		if ((joy2Btn(BUTTON_A) || joy2Btn(BUTTON_B)) && (joy2Btn(BUTTON_A) != joy2Btn(BUTTON_B))) {
			if (joy2Btn(BUTTON_A)) {
				// Open the gripper
				gripperState = 1;
			}

			if (joy2Btn(BUTTON_B)) {
				// Close the gripper
				gripperState = 0;
			}
		}

		// Get arm base pitch from joystick 1 on controller 2
		if (joystick.joy2_y1 >= 5) {
			servoArmPitchValue = 0;
		} else if (joystick.joy1_y2 <= -5) {
			servoArmPitchValue = 255;
		} else {
			servoArmPitchValue = 0;
		}

		// Get arm segment pitch from joystick 2 on controller 2
		if (joystick.joy2_y2 >= 5) {
			servoArmSegmentValue = 0;
		} else if (joystick.joy2_y2 <= -5) {
			servoArmSegmentValue = 255;
		} else {
			servoArmSegmentValue = 0;
		}

		// Allow other tasks to run
		EndTimeSlice();
	}
}

task screen() {
	while (true) {
		eraseDisplay();

		nxtDisplayTextLine(0, "Runtime: %i", averageRuntime);
		nxtDisplayTextLine(1, "Max: %i", driveMaxSpeed);
		nxtDisplayTextLine(2, "Left: %i", driveSpeedLeft);
		nxtDisplayTextLine(3, "Right: %i", driveSpeedRight);
		nxtDisplayTextLine(4, "Arm pitch: %i", servoArmPitchValue);
		nxtDisplayTextLine(5, "Arm segment pitch: %i", servoArmSegmentValue);

		wait1Msec(50);

		EndTimeSlice();
	}
}
